name: flyingumi
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=3_kmp_llvm
  - alsa-lib=1.2.14=hb9d3cd8_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.8.2=h59595ed_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - av=10.0.0=py311h572d6e2_4
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py311h1fdaa30_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311hd18a35c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - double-conversion=3.3.1=h5888daf_0
  - eigen=3.4.0=h00ab1b0_0
  - einops=0.8.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - fasteners=0.19=pyhd8ed1ab_1
  - ffmpeg=6.1.1=lgpl_h30e776b_4
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.1=py311h2dc5d0c_0
  - freeglut=3.2.2=hac7e632_2
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.22.9=hfa15dee_1
  - gstreamer=1.22.9=h98fc4e7_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=8.5.0=hfac3d4d_0
  - hdf5=1.14.3=nompi_h4f84152_100
  - hpack=4.1.0=pyhd8ed1ab_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.1.11=hfc55251_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.3.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.5=h1920b20_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang=19.1.7=default_hb5137d0_3
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp18.1=18.1.7=default_h9bb3924_0
  - libclang13=19.1.7=default_h9c6a7e4_3
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.80.2=hf974151_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.7=hb77312f_0
  - libllvm19=19.1.7=he89c38a_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopencv=4.9.0=qt6_py311hcc169a7_610
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2023.3.0=h2e90f83_3
  - libopenvino-auto-batch-plugin=2023.3.0=hd5fc58b_3
  - libopenvino-auto-plugin=2023.3.0=hd5fc58b_3
  - libopenvino-hetero-plugin=2023.3.0=h3ecfda7_3
  - libopenvino-intel-cpu-plugin=2023.3.0=h2e90f83_3
  - libopenvino-intel-gpu-plugin=2023.3.0=h2e90f83_3
  - libopenvino-ir-frontend=2023.3.0=h3ecfda7_3
  - libopenvino-onnx-frontend=2023.3.0=h61ff412_3
  - libopenvino-paddle-frontend=2023.3.0=h61ff412_3
  - libopenvino-pytorch-frontend=2023.3.0=h59595ed_3
  - libopenvino-tensorflow-frontend=2023.3.0=h76f315d_3
  - libopenvino-tensorflow-lite-frontend=2023.3.0=h59595ed_3
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.9=h87c4ccc_0
  - libprotobuf=4.24.4=hf27288f_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=256.9=h2774228_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.3.2=h658648e_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.13.8=hfdd30dd_0
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=20.1.6=h024ca30_0
  - llvmlite=0.44.0=py311hc1e8f15_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.0.3=py311hdb19cb5_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.20=hf484d3e_1001
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - ninja=1.11.0=h924138e_0
  - nomkl=3.0=0
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - numba=0.61.2=py311h4e1c48f_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - ocl-icd=2.3.2=h5eee18b_1
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openblas=0.3.29=h06a4308_0
  - openblas-devel=0.3.29=ha39b09d_0
  - opencv=4.9.0=qt6_py311hb77b0fa_610
  - openexr=3.2.2=haf962dd_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.5.0=h7b32b05_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py311h7db5c69_3
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - pixman=0.46.0=h29eaf8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.9.0=qt6_py311hf568a74_610
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.8=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=pyhe1237c8_2
  - pyzmq=26.2.0=py311h7deb3e3_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h112747c_20
  - qt-webengine=5.15.8=h3e791b3_6
  - qt6-main=6.6.3=hd0aab4e_0
  - qtwebkit=5.212=habbde2c_15
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=pyhd8ed1ab_1
  - sentry-sdk=2.29.1=pyhd8ed1ab_0
  - setproctitle=1.2.2=py311h5eee18b_2
  - setuptools=78.1.1=py311h06a4308_0
  - sip=6.7.12=py311hb755f60_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=1.8.0=h59595ed_0
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.1=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - wrapt=1.17.2=py311h9ecbd09_0
  - x264=1!152.20180806=h14c3975_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-cursor=0.1.4=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.22.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py311h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.0
      - accelerate==0.24.0
      - annotated-types==0.7.0
      - ansitable==0.11.4
      - attrs==25.3.0
      - casadi==3.7.0
      - cfgv==3.4.0
      - choreographer==1.0.9
      - cloudpickle==3.1.1
      - colored==2.3.0
      - control==0.10.1
      - crc32c==2.7.1
      - cython==3.1.2
      - diffusers==0.11.1
      - distlib==0.3.9
      - dm-control==1.0.30
      - dm-env==1.6
      - dm-tree==0.1.9
      - donfig==0.8.1.post1
      - egl-probe==1.0.2
      - etils==1.12.2
      - evdev==1.9.2
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - fsspec==2025.5.1
      - future-fstrings==1.2.0
      - glfw==2.9.0
      - grpcio==1.73.1
      - gymnasium==1.1.1
      - h5py==3.13.0
      - hf-xet==1.1.2
      - huggingface-hub==0.15.1
      - identify==2.6.12
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - jinja2==3.1.4
      - joblib==1.5.1
      - kaleido==1.0.0
      - kiwisolver==1.4.8
      - labmaze==1.0.6
      - logistro==1.1.0
      - loop-rate-limiters==1.1.0
      - lxml==5.4.0
      - markdown==3.8.2
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - mujoco==3.3.2
      - narwhals==1.42.0
      - networkx==3.5
      - nodeenv==1.9.1
      - numcodecs==0.11.0
      - numpy-quaternion==2024.0.8
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - orjson==3.11.0
      - pathlib2==2.3.7.post1
      - pillow==11.2.1
      - plotly==6.1.2
      - pre-commit==4.2.0
      - protobuf==6.31.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pynput==1.8.1
      - pyopengl==3.1.9
      - pyopengl-accelerate==3.1.9
      - python-xlib==0.33
      - qpsolvers==4.7.0
      - quadprog==0.1.13
      - regex==2024.11.6
      - robomimic==0.2.0
      - roma==1.5.3
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - simplejson==3.20.1
      - spatialmath-python==1.1.14
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - timm==0.9.7
      - torch==2.1.0
      - torchvision==0.16.0
      - triton==2.1.0
      - typing-inspection==0.4.1
      - virtualenv==20.31.2
      - wandb==0.20.1
      - werkzeug==3.1.3
      - zarr==2.12.0
      - mujoco-ar
prefix: /home/harsh/miniconda3/envs/flyingumi
